### ISSUE TITLE
annoying 1 pixel line after browser update

### ISSUE THREAD

**Issue by fr0zert** [Bali10050/FirefoxCSS#12]
аfter updating the browser, there is a gray line above all the elements on the left of the tabs.
windows 10
firefox 126.0

![image](https://github.com/Bali10050/FirefoxCSS/assets/52128237/855daf76-b97d-47e1-94fc-5ee963c998bb)

**Comment by Bali10050** [comment]
I can't fix it until monday, but if you can, a pull request is appriciated

**Comment by Bali10050** [comment]
Does cc55a93 fix your issue?

**Comment by fr0zert** [comment]
gona check it today, but a bit later

**Comment by fr0zert** [comment]
yes, thats fix the problem, ty!
