### ISSUE TITLE
enable preview tab feature 

### ISSUE THREAD

**Issue by nathish** [Bali10050/FirefoxCSS#13]
love how minimal and non-distracting this css is - thank you. 

I would like to make use of the preview tab when hovering the cursor over the tab. however, it's not working for me. Just a title box pops up. Is there a css snippet to enable this?

**Comment by Bali10050** [comment]
This feature is only in nightly at the moment, so it's inconsistent and easy to break. Also, the operating system you are using, your desktop environment, your display server, your gtk theme can have an effect on this, for example I use the latest archlinux with kde with the default kde gtk theme and it works for me. If you tell me what are you using I can try to help, but it might break after a few upgrades

https://github.com/user-attachments/assets/cafeb5e2-40c1-4b91-b53c-9d5f11550c91

**Comment by nathish** [comment]
sorry, ignore me. It was an issue with my nix config file not copying over the files to the right profile filepath. All works fine now thanks
