### ISSUE TITLE
minimize/close button color

### ISSUE THREAD

**Issue by dillonct** [Bali10050/FirefoxCSS#14]
![image](https://github.com/user-attachments/assets/57125b0d-d827-4f25-963e-72215c3bb26c)

I really like this style so far, but the issue I found is that the color of the minimize/restore/close/arrow below the '1' is black (really hard to see on a dark background like so). Even when I turn off my theme colors, it still remains black. Is there any way to have colors reflect the same as the number 1.

**Comment by Bali10050** [comment]
This is very common for some reason when firefox updates, I don't know why can't they leave those buttons alone and focus instead on something that anybody wants, anyways ebba2cf seems to fix the issue for now
![Screenshot_20240830_140155](https://github.com/user-attachments/assets/09e4be1a-2502-49be-b488-711de837a8ff)

**Comment by dillonct** [comment]
I am having the same issue with the added line from: https://github.com/Bali10050/FirefoxCSS/commit/c991b0bf602894a52197b28a22e9528dfbe901ae. Does it still work on your end?

**Comment by Bali10050** [comment]
Yes, can you tell me what os are you using? Also, did you put the `user.js` file in your profile folder? If not, try changing `svg.context-properties.content.enabled` to `true` in `about:config

https://github.com/user-attachments/assets/191c5357-8866-47f3-b963-95ae9751711d

**Comment by dillonct** [comment]
I am using Linux/KDE Plasma. I didn't add the user.js files, just the chrome folder. Setting ```svg.context-properties.content.enabled``` to ```true``` in ```about:config``` fixed the issue. Thank you! :)

**Comment by dillonct** [comment]
Just a suggestion, I think it would be nice to leave a note in the README.md to pay closer attention to ```user.js``` if they want to add the file or manually configure in the ```about:config```.

**Comment by Bali10050** [comment]
I recommend also setting `layout.css.has-selector.enabled` to `true`, because there are some things in this css that can only be done with the `:has` selector, and yes a note would be a good idea
