### ISSUE TITLE
Broken video player

### ISSUE THREAD

**Issue by fr0zert** [Bali10050/FirefoxCSS#16]
Recently found that on one site are broken player, no buttons and no video window.
I think the problem is that custom css parameters have the same names as elements on the site, or something like that, but this is just my guess.
Site: rezka.ag (they have many different domains hdrezka and etc.)

broken:
![image](https://github.com/user-attachments/assets/dfdc867d-657a-403e-8838-e62e2e74715b)

normal(without css):
![image](https://github.com/user-attachments/assets/9eb62089-1251-4bff-afee-c83ebaae42c1)

**Comment by Bali10050** [comment]
`userContent.css` can have an effect on websites, but I put everything in media-tags limited to some urls, so it shouldn't do anything outside of `about:` and `chrome:` unless there's a typo somewhere. Try checking it in a new profile, until I get home to fix it.

**Comment by Bali10050** [comment]
It wasn't anything that I tought of, the css that changed the background color in `about:blank`, somehow disabled the videoplayer.

**Comment by fr0zert** [comment]
bug report to mozilla?

**Comment by Bali10050** [comment]
No, you just need to update your `userContent.css` and your `user.js`

**Comment by fr0zert** [comment]
oh ok, ty!
