### ISSUE TITLE
Extra scrollbar

### ISSUE THREAD

**Issue by fr0zert** [Bali10050/FirefoxCSS#17]
Recently visiting different sites noticed that I see an additional scrollbar, because of this sometimes happens that they are two at once, not on all sites.

For example, I took tiktok which shows an additional scrollbar in a certain situation, when you open a "full-screen" video in your profile(liked or in favorites), it shows up.

you can see two scrollbars on the right
![image](https://github.com/user-attachments/assets/30812d99-9f11-4d49-9a0c-537d886585e8)

normally like this
![image](https://github.com/user-attachments/assets/74b37180-65d8-42c9-94a6-5160c4d6e55d)

Have seen the same scroll on various other sites, under random circumstances, can't recall examples yet.

**Comment by Bali10050** [comment]
Try 6882bab
