### ISSUE TITLE
"List all tabs" button incorrect position

### ISSUE THREAD

**Issue by breakfastpizza** [Bali10050/FirefoxCSS#18]
Just tried this style on MacOS with Firefox v131.0 and the "list all tabs" button on the right side looks like it's in the wrong position

<img width="1520" alt="Screenshot 2024-10-08 at 4 59 51 PM" src="https://github.com/user-attachments/assets/4ee4a994-6575-4a51-af14-cd8cc81403ad">

The issue persists regardless of window size. Not sure if I did something wrong while installing or if this is a bug. Otherwise this looks awesome so thank you for sharing!

**Comment by Bali10050** [comment]
a11c66b seems to mostly fix the issue
![Screenshot_20241011_162520](https://github.com/user-attachments/assets/653f7185-45f1-49b7-b5d8-ce291f6ec182)

**Comment by breakfastpizza** [comment]
Yes that fixed the issue for me. Thanks!
