### ISSUE TITLE
Forward button not adjustable in customise toolbar

### ISSUE THREAD

**Issue by mynameisKaiser** [Bali10050/FirefoxCSS#23]
Hi, as stated in the title, when i use the customise toolbar option, the forward button stays in front of the urlbar no matter where its dragged in the config state
e.g.
<img width="579" alt="image" src="https://github.com/user-attachments/assets/9dd4ece0-58a0-4c3a-b07e-42d0a7ffb640">
<img width="570" alt="image" src="https://github.com/user-attachments/assets/6646fd13-7af8-4553-a8ce-506d77c8a97d">

OS: macOS Sonoma 14.3.1 (23D60) 

(also there are some options that are greyed out that cannot be removed)

**Comment by mynameisKaiser** [comment]
1st image is in config state, second image is in normal state

**Comment by Bali10050** [comment]
You can drag the button, but it's a bit harder at the moment, firefox doesn't seem to like `#nav-bar{direction: rtl;}` anymore. Please try 77008d8, it should fix the issue

https://github.com/user-attachments/assets/cdfbf685-8f23-4191-b4fd-b4b79ab28eab

**Comment by Bali10050** [comment]
77008d8 wasn't it, macos seems to use different code for the drag and drop ui, 930c66f makes it work, but you need to manually change the order for everything.

**Comment by mynameisKaiser** [comment]
Hey, it worked, thanks for the fix! I'll close this issue now :)
![image](https://github.com/user-attachments/assets/03bc0c13-f73d-4bcf-a6f8-8076a77b53bc)
