### ISSUE TITLE
Pinned extensions overlapping with menu button.

### ISSUE THREAD

**Issue by bbogdn2** [Bali10050/FirefoxCSS#3]
It seems when enough extensions are pinned, it will overlap with the menu button like so:
![image](https://github.com/Bali10050/FirefoxCSS/assets/133264129/c6a79c54-ab22-4746-ad49-34777984e02c)

**Comment by Bali10050** [comment]
You are not the only one telling me this, but I cannot reproduce this issue on my computer.

![Screenshot_20230612_013248](https://github.com/Bali10050/FirefoxCSS/assets/110120798/72901748-1fa3-4771-bac1-dc3152e2b234)

**Comment by bbogdn2** [comment]
Hmm... maybe it's a windows 11 issue...
The problem usually happens to me when I maximize and restore Firefox.

**Comment by Bali10050** [comment]
Can you try to do something about it?

**Comment by Bali10050** [comment]
I think I fixed it.
