### ISSUE TITLE
How do I change it to dark mode?

### ISSUE THREAD

**Issue by Garudine** [Bali10050/FirefoxCSS#4]
Thanks for your effort, it looks and it works great! The only problem I have is that the whole color scheme is in light mode and I can't find a way to change it. I've changed my settings in firefox and windows to make it dark mode, but it stills looks the same. I could touch the overall code, but I rather not break anything just in case. I would like for it to look like the preview image you have in your read me file. 

That's all! Thanks a lot!

**Comment by Bali10050** [comment]
![Screenshot_20230702_042252](https://github.com/Bali10050/FirefoxCSS/assets/110120798/2110b6ad-7e06-4fb8-a246-70ca8b9d7e97)

Try it on a new profile, or try installing another firefox theme like this:
<https://addons.mozilla.org/en-US/firefox/addon/beautiful-chrome-dark/reviews/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=addons-manager-reviews-link>
