### ISSUE TITLE
Firefox theme

### ISSUE THREAD

**Issue by markelrlopez** [Bali10050/FirefoxCSS#7]
Which firefox theme do u use? Is the dark default one or specific one. Because with the default one the inspect button appear with othe dark color (#23222B)

**Comment by Bali10050** [comment]
It's the default theme in linux, I don't really know anything else about it.

**Comment by matti-kz** [comment]
You can do general search for "gruvbox" in Firefox addon store. I found this one to be most similar in Windows to the screenshots https://addons.mozilla.org/en-US/firefox/addon/gruvbox-dark-hard
aside from the background color on a new tab, if you know the css property to change that let me know
