### ISSUE TITLE
An option to always show favicons?

### ISSUE THREAD

**Issue by LennyLizowzskiy** [Bali10050/FirefoxCSS#8]
Hi. Right now icons appear only when you're hovering the tab or some item in favorites bar. Can you make an option to make icons always appear?

**Comment by Bali10050** [comment]
You just need to remove the `/` from the end of this line:
https://github.com/Bali10050/FirefoxCSS/blob/859cbc1ed76430ffe5bfb85961b825f215c3b4c1/userChrome.css#L54

**Comment by LennyLizowzskiy** [comment]
Nice, thanks
